services:
  postgres:
    image: postgres:16
    container_name: postgres_springboot
    environment:
      POSTGRES_DB: proyectofinaldb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network
    
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/proyectofinaldb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_RELATIVE_PATH: "/auth"
      # Configuración CORS
      KC_SPI_EVENTS_LISTENER: "jboss-logging"
      KC_CORS: "true"
      KC_CORS_ALLOWED_ORIGINS: "http://localhost:3000"
      KC_CORS_ALLOWED_METHODS: "POST, PUT, DELETE, GET, OPTIONS"
      KC_CORS_ALLOWED_HEADERS: "X-Requested-With, Content-Type, Authorization, Origin, Accept"
      KC_CORS_EXPOSED_HEADERS: "Location"
      KC_CORS_ALLOW_CREDENTIALS: "true"
    command: 
      - start-dev
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak-cors.conf:/opt/keycloak/conf/keycloak.conf.d/cors.conf
    depends_on:
      - postgres
    restart: always
    networks:
      - app-network

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/proyectofinaldb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak
    restart: always
    networks:
      - app-network

  nextjs-app:
    build:
      context: ./inventory-management-system
      dockerfile: Dockerfile
    container_name: nextjs_app
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_KEYCLOAK_URL=http://localhost:8180/auth
    ports:
      - "3000:3000"
    depends_on:
      - springboot-app
    restart: always
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
