services:
  postgres:
    image: postgres:17
    container_name: postgres_springboot
    environment:
      POSTGRES_DB: proyectofinaldb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    ports:
      - "9090:9090"
    environment:
      # Credenciales de admin inicial
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      # Montamos tu exportación bajo el directorio de importación de Keycloak
      - ./realm-config/realm.json:/opt/keycloak/data/import/realm.json
    # Inicia en modo desarrollo e importa cualquier JSON en data/import
    command: ["start-dev","--http-port=9090","--import-realm"]

volumes:
  postgres_data:
