CREATE TABLE producto
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre           VARCHAR(255),
    descripcion      VARCHAR(255),
    categoria        VARCHAR(255),
    precio           DOUBLE PRECISION                        NOT NULL,
    cantidad_inicial INTEGER                                 NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_producto PRIMARY KEY (id)
);

CREATE TABLE usuario
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

CREATE TABLE usuario_roles
(
    usuario_id BIGINT NOT NULL,
    roles      VARCHAR(255)
);

ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_username UNIQUE (username);

ALTER TABLE usuario_roles
    ADD CONSTRAINT fk_usuario_roles_on_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id);