CREATE TABLE producto
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre           VARCHAR(255),
    descripcion      VARCHAR(255),
    categoria        VARCHAR(255),
    precio           DOUBLE PRECISION                        NOT NULL,
    cantidad_inicial INTEGER                                 NOT NULL,
    CONSTRAINT pk_producto PRIMARY KEY (id)
);

INSERT INTO producto (categoria, descripcion, "nombre", precio, cantidad_inicial) VALUES
('Electrónicos', 'Laptop de alta gama con 16GB RAM y 512GB SSD', 'Laptop Pro', 1200.0, 10),
('Hogar', 'Escritorio de oficina de madera con cajones', 'Escritorio de Oficina', 350.0, 5),
('Otros', 'Zapatos ligeros para correr', 'Zapatos para Correr', 75.0, 20),
('Hogar', 'Manzanas orgánicas frescas de granja local', 'Manzanas Orgánicas', 3.5, 100),
('Gaming', 'Oso de peluche suave', 'Oso de Peluche', 25.0, 40),
('Otros', 'Novela épica de fantasía con dragones', 'Novela de Fantasía', 15.0, 30),
('Gaming', 'Balón de fútbol aprobado por la FIFA', 'Balón de Fútbol', 30.0, 25),
('Accesorios', 'Champú natural con aloe vera', 'Champú', 8.99, 50),
('Accesorios', 'Cargador rápido USB para auto', 'Cargador de Auto', 14.99, 35),
('Accesorios', 'Tabletas de Vitamina C de 1000mg', 'Vitamina C', 12.5, 60);

INSERT INTO producto (categoria, descripcion, "nombre", precio, cantidad_inicial) VALUES
('Electrónicos', 'Auriculares inalámbricos con cancelación de ruido', 'Auriculares Bluetooth', 89.99, 15),
('Hogar', 'Mesa de comedor moderna de vidrio', 'Mesa de Comedor', 500.0, 2),
('Otros', 'Chaqueta impermeable y aislada', 'Chaqueta de Invierno', 120.0, 12),
('Hogar', 'Leche entera orgánica de 1 litro', 'Leche', 1.99, 80),
('Gaming', 'Auto deportivo a control remoto', 'Auto RC', 45.0, 18),
('Otros', 'Libro avanzado de física para secundaria', 'Libro de Física', 60.0, 22),
('Gaming', 'Tapete antideslizante para yoga y pilates', 'Tapete de Yoga', 22.0, 35),
('Accesorios', 'Crema facial anti-edad con retinol', 'Crema Facial', 34.5, 25),
('Accesorios', 'Limpiaparabrisas para todas las estaciones', 'Limpiaparabrisas', 19.99, 30),
('Accesorios', 'Tabletas de ibuprofeno de 200mg', 'Analgésico', 6.99, 100);

INSERT INTO producto (categoria, descripcion, "nombre", precio, cantidad_inicial) VALUES
('Electrónicos', 'Modelo más reciente con pantalla AMOLED', 'Smartphone', 899.0, 8),
('Hogar', 'Librero de madera de 5 niveles', 'Librero', 120.0, 6),
('Otros', 'Jeans ajustados de color azul', 'Jeans', 40.0, 18),
('Hogar', 'Pan integral en barra', 'Pan', 2.5, 70),
('Gaming', 'Set creativo de bloques de construcción', 'Set de Lego', 60.0, 20),
('Otros', 'Historia detectivesca cautivadora', 'Novela de Misterio', 10.0, 28),
('Gaming', 'Raqueta de tenis de grado profesional', 'Raqueta de Tenis', 90.0, 10),
('Accesorios', 'Labial mate de larga duración', 'Labial', 12.0, 40),
('Accesorios', 'Ambientador para auto con aroma cítrico', 'Ambientador', 5.0, 45),
('Accesorios', 'Kit compacto de emergencia para hogar o viaje', 'Botiquín de Primeros Auxilios', 25.0, 15);

CREATE TABLE usuario
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

CREATE TABLE usuario_roles
(
    usuario_id BIGINT NOT NULL,
    roles      VARCHAR(255)
);

ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_username UNIQUE (username);

ALTER TABLE usuario_roles
    ADD CONSTRAINT fk_usuario_roles_on_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id);